{% set version = "0.43.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mpmi
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mpmi_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mpmi/mpmi_{{ version }}.tar.gz
  sha256: 1313c6b742546f9c276f3eba4aa4071eed69211932a7a61ad25094bf9148e7d3
  patches:  # [win]
    - Makevars.patch  # [win]

build:
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_fortran') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-kernsmooth
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-kernsmooth

test:
  commands:
    - $R -e "library('mpmi')"           # [not win]
    - "\"%R%\" -e \"library('mpmi')\""  # [win]

about:
  home: http://r-forge.r-project.org/projects/mpmi/
  license: GPL-3.0-only
  summary: 'Uses a kernel smoothing approach to calculate Mutual Information for comparisons between all types of variables including continuous vs continuous, continuous vs discrete and discrete vs discrete. Uses a nonparametric bias correction giving Bias Corrected Mutual Information (BCMI). Implemented efficiently in
    Fortran 95 with OpenMP and suited to large genomic datasets.  '
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - Chris-Lowe-Integrity

# Package: mpmi
# Type: Package
# Title: Mixed-Pair Mutual Information Estimators
# Version: 0.43
# Date: 2019-04-22
# Author: Chris Pardy
# Maintainer: Chris Pardy <cooliomcdude@gmail.com>
# Description: Uses a kernel smoothing approach to calculate Mutual Information for comparisons between all types of variables including continuous vs continuous, continuous vs discrete and discrete vs discrete. Uses a nonparametric bias correction giving Bias Corrected Mutual Information (BCMI). Implemented efficiently in Fortran 95 with OpenMP and suited to large genomic datasets.
# License: GPL-3
# URL: http://r-forge.r-project.org/projects/mpmi/
# Depends: KernSmooth
# NeedsCompilation: yes
# Packaged: 2019-04-22 06:12:27 UTC; cp
# Repository: CRAN
# Date/Publication: 2019-04-22 06:40:03 UTC
