# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_c_compilerclangfortran_compilergfortrantarget_platformosx-64
    - CONFIG=osx_c_compilertoolchain_cfortran_compilertoolchain_forttarget_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "n2ONbjlW+9eIpbXmDBLgwBQKBp898BN+YLwomhwaqgYjRvtpC6eoL4aYkhDG0lR1W5zPJl4350tZSGl2JwPKgvIHCa+Q7GvHTorIVXToQPW4hiYIwuFiH/c1DyEoKUxaWnYt2zv0kaR+O7Wq3gR8hOUrLPTwNAfaN26u5kq3kHmBorWAGxvF+jNoNojOKzpW4T/84SbybrGatCwf2nQHk1WRkSfcgR5jYYennBZ59Mv0yG9unkW+4vNKl4eUs0I0kKtUmLOn1fA70/JLCS1us0/p8pX0xrFbDVIEzILflnx/bxyzLG8WRAAGn7K13mLe1wfHtc+kOh/ubTVxsD4sJ+0ybsIJ7sCy01lZV+0UmmYvO3H0IKSwZIy+Vo3fiUuITzKoWwa1xObOMJ0FJmo81HZun7f44nr8iXdO1lROsYVNXykE9Ee2x8RVHKF/06VpWMKwb3qsHTbQ+hghLLtJpFnbyoPqPUsuD7CCGvtqsCZgxIG2s0oLo99PLuIbg62L/FYq99pwIIzLigRA0bYeIBTHtHs9pt5dyv1XD06KS/U72ls4c1LCahi2iYZmjwQkijZ6D+NNJpN6yE5QyXjAB8N3cIRt0d08JBH4I+B1AeWXFyrUZNb9iNo4xCXn9h8GjxL/l1bijc34cnAKSOY/qTz/vISz24vcL6+rrCUxmh0="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
