travis:
  secure:
    BINSTAR_TOKEN: VOnI2aDQPxYB0PclNWykrEhnl1HRGopa3LbmzFn+zxn4xuaM/1c/rduMLomKJdEJ6ZBstpTmMKE+O9/NQkE+QjCNDIkjRD7S0YPVnQbQgiixbacaPwNfwU/YRjp8iOqQXG6s5KHVbqWWtTe9LcTxKiwr2xNGL9QHDFGv9wLoJd5DSkEjLgaNxbn2E5gUtroW9uJg2Mz/PuO2UJpGZRKyzjQBwZmGi+vz7FDpVO55R4d9E6wxVxYnyGSUNMOA4UUvPvmAHi0TJpDELucsVk+OGH//fJQeiM1oZF1ciRk7Zpm6OX2RQKt6IYIcduF1i918zIBeXXN6Nrct/ctu0Rhmf9k0MlSSm67ukRfZ3ozq3g+d+ygn7jOTTqIcvx1hJzSSDySI2hpScceLNGYeZ7CRmew8qBvb3nFXsL/evJNpI4eZx50qwskcXIeMtjmzFjq+eztk0JpsUDyKN1ixTQR7VU+wm6RnpkjRwcWBEEEdfGBqBRL7kr4k2erCjMOBxd1IMUpR8vTXKpivlzQIn0rSOvf3SFPz7NgwC1s4dx8f8B62EzSBkQVNVnJ+NJRUKTV/7LwTj+G2nBvgL7m5fr+lz9/mRCKM9lIUhKVbwGEsejWbS+25T8K6/vyzP4YSltWLR4cxYyrjdqjOTbUOcPwuVIaAe5ycd96zXzaF0nAPphc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
