appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: n2ONbjlW+9eIpbXmDBLgwBQKBp898BN+YLwomhwaqgYjRvtpC6eoL4aYkhDG0lR1W5zPJl4350tZSGl2JwPKgvIHCa+Q7GvHTorIVXToQPW4hiYIwuFiH/c1DyEoKUxaWnYt2zv0kaR+O7Wq3gR8hOUrLPTwNAfaN26u5kq3kHmBorWAGxvF+jNoNojOKzpW4T/84SbybrGatCwf2nQHk1WRkSfcgR5jYYennBZ59Mv0yG9unkW+4vNKl4eUs0I0kKtUmLOn1fA70/JLCS1us0/p8pX0xrFbDVIEzILflnx/bxyzLG8WRAAGn7K13mLe1wfHtc+kOh/ubTVxsD4sJ+0ybsIJ7sCy01lZV+0UmmYvO3H0IKSwZIy+Vo3fiUuITzKoWwa1xObOMJ0FJmo81HZun7f44nr8iXdO1lROsYVNXykE9Ee2x8RVHKF/06VpWMKwb3qsHTbQ+hghLLtJpFnbyoPqPUsuD7CCGvtqsCZgxIG2s0oLo99PLuIbg62L/FYq99pwIIzLigRA0bYeIBTHtHs9pt5dyv1XD06KS/U72ls4c1LCahi2iYZmjwQkijZ6D+NNJpN6yE5QyXjAB8N3cIRt0d08JBH4I+B1AeWXFyrUZNb9iNo4xCXn9h8GjxL/l1bijc34cnAKSOY/qTz/vISz24vcL6+rrCUxmh0=}
